DROP DATABASE IF EXISTS data_warehouse;

CREATE DATABASE data_warehouse;

USE data_warehouse;

DROP TABLE IF EXISTS dim_voltage;
CREATE TABLE dim_voltage (
    VOLTAGE_ID INT,
    V_LEVEL VARCHAR(255),
    PRIMARY KEY (VOLTAGE_ID)
);

DROP TABLE IF EXISTS dim_location;
CREATE TABLE dim_location (
    LOCATION_ID INT,
    DISTRICT_NAME VARCHAR(255),
    MUNICIPALITY_NAME VARCHAR(255),
    PARISH VARCHAR(255),
    PRIMARY KEY (LOCATION_ID)
);

DROP TABLE IF EXISTS dim_time;
CREATE TABLE dim_time (
    TIME_ID INT,
    YEAR_ID INT,
    MONTH_ID INT,
    PRIMARY KEY (TIME_ID)
);

DROP TABLE IF EXISTS fact_table;
CREATE TABLE fact_table (
    ENERGY_CONSUMPTION DOUBLE,
    TIME_ID INT,
    LOCATION_ID INT,
    VOLTAGE_ID INT,
    PRIMARY KEY (TIME_ID, LOCATION_ID, VOLTAGE_ID),
    FOREIGN KEY (TIME_ID) REFERENCES dim_time (TIME_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES dim_location (LOCATION_ID),
    FOREIGN KEY (VOLTAGE_ID) REFERENCES dim_voltage (VOLTAGE_ID)
);
